### ISSUE TITLE
Issue: CSS Not Loading When Running bin/server

### ISSUE THREAD

**Issue by bchandhu** [appdev-projects/sinatra-template#16]
#### Description
When running the app with `ruby app.rb`, the CSS loads and the UI is styled correctly. However, when running the app with `bin/server`, the CSS is missing, and the UI appears unstyled.

#### Solution
Adding the following to the `config.ru` file fixed the issue:

```ruby
set :public_folder, 'public'
set :static, true
```
This code ensures that Sinatra will serve static files (such as CSS) from the public/ folder when running the app with rackup or bin/server.

**Comment by bpurinton** [comment]
Thanks for the note! Can you have a look at #17 and let me know if that's what you meant by the fix for this?

**Comment by bchandhu** [comment]
Yes, correct. Thank you Ben!
