### ISSUE TITLE
Issue with 'bin/dev' Command Not Responding in Terminal

### ISSUE THREAD

**Issue by Meenoow** [appdev-projects/sinatra-template#9]
_Issue Description:_
I am experiencing an issue where the 'bin/dev' command is not responding in the terminal. To resolve this, I attempted to delete the Codespace and load a new one. **The steps worked and it is behaving normally.** 

_Steps to Reproduce:_
Clone the repository.
Navigate to the project directory.
Attempt to execute the 'bin/dev' command in the terminal.

_Expected Behavior:_
The 'bin/dev' command should run and execute without any issues, allowing me to perform development tasks.

_Actual Behavior:_
When I run 'bin/dev' in the terminal, it does not respond, and the error message displays: **/home/student/.rvm/ruby-3.2.1/bin/rackup: 6: exec: /home/student/.rvm/ruby-3.2.1/bin/ruby: not found.** Version of ruby verified through terminal and displays it is the current and default version.

**Comment by bpurinton** [comment]
Sorry about that issue. If you want to try and avoid issues like this with codespaces, one option is to install a local Ruby + Rails development environment. That comes with some complications, and it may not go smoothly. But if you feel comfortable trying that; here's our lesson with instructions: https://learn.firstdraft.com/lessons/49-local-setup
